<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JKGLUOh' shared service.

return $this->privates['.service_locator.JKGLUOh'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('serializer' => function () {
    return ($this->services['serializer'] ?? $this->getSerializerService());
}));
