<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._QsEhhI' shared service.

return $this->privates['.service_locator._QsEhhI'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('saleLogger' => function (): \App\Logger\SaleLogger {
    return ($this->privates['App\Logger\SaleLogger'] ?? $this->load('getSaleLoggerService.php'));
}));
