<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRaTF0b\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRaTF0b/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCRaTF0b.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCRaTF0b\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCRaTF0b\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CRaTF0b',
    'container.build_id' => '57ccd30d',
    'container.build_time' => 1539614995,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRaTF0b');
