<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Logger\SaleLogger' shared autowired service.

include_once $this->targetDirs[3].'/src/Logger/SaleLogger.php';

return $this->privates['App\Logger\SaleLogger'] = new \App\Logger\SaleLogger(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
